// Appearances feature module
// Contains all appearance-related functionality

// Public modules
pub mod commands;
pub mod parsers;
pub mod types;

// Re-export commonly used types
pub use commands::AppearanceCategory;
pub use types::*;

// Re-export from core (generated by build.rs)
pub use crate::core::protobuf::Appearances;
