// Core module - shared utilities
// Feature-specific code moved to src/features/

pub mod cache;
pub mod errors;
pub mod lzma;
pub mod protobuf; // Generated by build.rs from .proto files
pub mod validation;

// Re-export commonly used types
pub use cache::{CacheStats, LRUCache};
pub use errors::{AppError, AppResult};
