pub mod core;
pub mod features;
pub mod state;

use features::sounds::commands::SoundsState;
use state::AppState;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    // Initialize logger
    env_logger::Builder::from_env(env_logger::Env::default().default_filter_or("debug")).init();

    log::info!("Starting Tibia Assets Editor - EXTREME PERFORMANCE MODE");

    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_dialog::init())
        .manage(AppState::new()) // ✅ OPTIMIZED: Uses LRU caches with bounds
        .manage(SoundsState::new())
        .invoke_handler(tauri::generate_handler![
            // Appearances API
            features::appearances::commands::load_appearances_file,
            features::appearances::commands::get_appearance_stats,
            features::appearances::commands::select_tibia_directory,
            features::appearances::commands::list_appearance_files,
            features::appearances::commands::list_appearances_by_category,
            features::appearances::commands::find_appearance_position,
            features::appearances::commands::get_appearance_details,
            features::appearances::commands::get_appearance_count,
            features::appearances::commands::get_item_subcategories,
            features::appearances::commands::get_complete_appearance,
            features::appearances::commands::get_special_meaning_ids,
            features::appearances::commands::update_appearance_name,
            features::appearances::commands::update_appearance_description,
            features::appearances::commands::update_appearance_flag_bool,
            features::appearances::commands::update_appearance_light,
            features::appearances::commands::update_appearance_shift,
            features::appearances::commands::update_appearance_height,
            features::appearances::commands::update_appearance_write,
            features::appearances::commands::update_appearance_write_once,
            features::appearances::commands::update_appearance_automap,
            features::appearances::commands::update_appearance_hook,
            features::appearances::commands::update_appearance_lenshelp,
            features::appearances::commands::update_appearance_clothes,
            features::appearances::commands::update_appearance_default_action,
            features::appearances::commands::update_appearance_market,
            features::appearances::commands::update_appearance_bank,
            features::appearances::commands::update_appearance_changed_to_expire,
            features::appearances::commands::update_appearance_cyclopedia_item,
            features::appearances::commands::update_appearance_upgrade_classification,
            features::appearances::commands::update_appearance_skillwheel_gem,
            features::appearances::commands::update_appearance_imbueable,
            features::appearances::commands::update_appearance_proficiency,
            features::appearances::commands::update_appearance_transparency_level,
            features::appearances::commands::update_appearance_weapon_type,
            features::appearances::commands::update_appearance_minimum_level,
            features::appearances::commands::update_appearance_restrict_to_vocation,
            features::appearances::commands::update_appearance_npc_sale_data,
            features::appearances::commands::update_appearance_texture_settings,
            features::appearances::commands::replace_appearance_sprites,
            features::appearances::commands::remove_appearance_sprites,
            features::appearances::commands::append_appearance_sprites,
            features::appearances::commands::save_appearances_file,
            features::appearances::commands::export_appearance_to_json,
            features::appearances::commands::export_appearance_to_aec,
            features::appearances::commands::import_appearance_from_json,
            features::appearances::commands::import_appearances_from_files,
            features::appearances::commands::import_appearances_from_files_all,
            features::appearances::commands::get_import_context,
            features::appearances::commands::duplicate_appearance,
            features::appearances::commands::create_empty_appearance,
            features::appearances::commands::copy_appearance_flags,
            features::appearances::commands::paste_appearance_flags,
            features::appearances::commands::delete_appearance,
            // Sprites API
            features::sprites::commands::load_sprites_catalog,
            features::sprites::commands::auto_load_sprites,
            features::sprites::commands::get_sprite_by_id,
            features::sprites::commands::get_appearance_sprites,
            features::sprites::commands::get_appearance_preview_sprite,
            features::sprites::commands::clear_sprite_cache,
            features::sprites::commands::get_sprite_cache_stats,
            // Batch sprite loading - MASSIVE performance boost for preview grids
            features::sprites::commands::get_appearance_sprites_batch,
            features::sprites::commands::get_appearance_preview_sprites_batch,
            // Sounds API
            features::sounds::commands::load_sounds_file,
            features::sounds::commands::get_sounds_stats,
            features::sounds::commands::list_sound_types,
            features::sounds::commands::get_sound_by_id,
            features::sounds::commands::get_sounds_by_type,
            features::sounds::commands::list_all_sounds,
            features::sounds::commands::list_numeric_sound_effects,
            features::sounds::commands::get_sound_effect_count,
            features::sounds::commands::get_sound_audio_data,
            features::sounds::commands::get_sound_file_path,
            features::sounds::commands::get_numeric_sound_effect_by_id,
            features::sounds::commands::list_ambience_streams,
            features::sounds::commands::get_ambience_stream_by_id,
            features::sounds::commands::get_ambience_stream_count,
            features::sounds::commands::list_ambience_object_streams,
            features::sounds::commands::get_ambience_object_stream_by_id,
            features::sounds::commands::get_ambience_object_stream_count,
            features::sounds::commands::list_music_templates,
            features::sounds::commands::get_music_template_by_id,
            features::sounds::commands::get_music_template_count,
            features::sounds::commands::update_sound_info,
            features::sounds::commands::update_numeric_sound_effect,
            features::sounds::commands::update_ambience_stream,
            features::sounds::commands::update_ambience_object_stream,
            features::sounds::commands::update_music_template,
            features::sounds::commands::save_sounds_file,
            features::sounds::commands::add_sound,
            features::sounds::commands::delete_sound,
            features::sounds::commands::add_numeric_sound_effect,
            features::sounds::commands::delete_numeric_sound_effect,
            features::sounds::commands::import_and_add_sound,
            // Monsters API
            features::monsters::commands::list_monster_files,
            features::monsters::commands::load_monster_file,
            features::monsters::commands::save_monster_file,
            features::monsters::commands::rename_monster_file,
            features::monsters::commands::list_bestiary_classes,
            // Npcs API
            features::npcs::commands::list_npc_files,
            features::npcs::commands::load_npc_file,
            features::npcs::commands::save_npc_file,
            features::npcs::commands::rename_npc_file,
            features::npcs::commands::sync_npc_shops_from_proto,
            // Settings API
            features::settings::set_tibia_base_path,
            features::settings::get_tibia_base_path,
            features::settings::set_monster_base_path,
            features::settings::get_monster_base_path,
            features::settings::set_npc_base_path,
            features::settings::get_npc_base_path,
            // StaticData & StaticMapData
            features::staticdata::commands::io::load_staticdata_file,
            features::staticdata::commands::io::list_staticdata_files,
            features::staticdata::commands::io::save_staticdata_file,
            features::staticdata::commands::io::remove_staticdata_item,
            features::staticdata::commands::io::update_staticdata_creature,
            features::staticdata::commands::io::update_staticdata_boss,
            features::staticdata::commands::io::update_staticdata_quest,
            features::staticdata::commands::io::update_staticdata_title,
            features::staticdata::commands::io::get_staticdata_creatures,
            features::staticdata::commands::io::get_staticdata_titles,
            features::staticdata::commands::io::get_staticdata_houses,
            features::staticdata::commands::io::get_staticdata_bosses,
            features::staticdata::commands::io::get_staticdata_quests,
            features::staticmapdata::commands::io::load_staticmapdata_file,
            features::staticmapdata::commands::io::list_staticmapdata_files,
            features::staticmapdata::commands::io::get_staticmapdata_houses,
            // QM Translation Editor API
            features::qm::commands::qm_find_files,
            features::qm::commands::qm_load,
            features::qm::commands::qm_get_entries,
            features::qm::commands::qm_update_translation,
            features::qm::commands::qm_update_translations,
            features::qm::commands::qm_save,
            features::qm::commands::qm_export_csv,
            features::qm::commands::qm_import_csv,
            features::qm::commands::qm_debug_raw,
            // RCC Editor API
            features::rcc::commands::rcc_load,
            features::rcc::commands::rcc_get_resource,
            features::rcc::commands::rcc_replace_resource,
            features::rcc::commands::rcc_save,
            features::rcc::commands::rcc_extract_all,
            features::rcc::commands::rcc_extract_single,
            features::rcc::commands::rcc_get_files,
            features::rcc::commands::rcc_replace_from_file,
            features::rcc::commands::rcc_delete_resource,
            features::rcc::commands::rcc_find_files,
            features::rcc::commands::rcc_add_resource,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
