name: Build Debug

on:
  push:
    branches-ignore:
      - main
    paths:
      - "src/**"
      - "src-tauri/**"
      - "package.json"
      - "package-lock.json"
      - "vite.config.*"
  pull_request:
    paths:
      - "src/**"
      - "src-tauri/**"
      - "package.json"
      - "package-lock.json"
      - "vite.config.*"
  workflow_dispatch:

jobs:
  build-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
          repository: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name || github.repository }}
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo/target
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri

      - name: Build Tauri (debug)
        run: npm run tauri build -- --debug

      - name: Upload debug bundle
        uses: actions/upload-artifact@v4
        with:
          name: tauri-debug-bundle
          path: src-tauri/target/debug/bundle
