name: Tauri Build Debug (Linux)

on:
  push:
    branches-ignore:
      - main
    paths:
      - "src/**"
      - "src-tauri/**"
      - "package.json"
      - "package-lock.json"
      - "vite.config.*"
      - "src-tauri/Cargo.toml"
      - "src-tauri/Cargo.lock"
  pull_request:
    paths:
      - "src/**"
      - "src-tauri/**"
      - "package.json"
      - "package-lock.json"
      - "vite.config.*"
      - "src-tauri/Cargo.toml"
      - "src-tauri/Cargo.lock"
  workflow_dispatch:

jobs:
  tauri-build-debug-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (PR → head; outros → ref)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
          repository: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name || github.repository }}
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install frontend deps
        run: npm ci

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Linux system deps for Tauri bundler (GTK/WebKit, both 4.1/4.0)
        shell: bash
        run: |
          set -euo pipefail
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            pkg-config \
            patchelf
          if apt-cache show libwebkit2gtk-4.1-dev >/dev/null 2>&1; then
            sudo apt-get install -y libwebkit2gtk-4.1-dev
          elif apt-cache show libwebkit2gtk-4.0-dev >/dev/null 2>&1; then
            sudo apt-get install -y libwebkit2gtk-4.0-dev
          else
            echo "Nenhuma variante libwebkit2gtk (-4.1-dev ou -4.0-dev) encontrada no runner." >&2
            exit 1
          fi

      - name: Cache cargo/target
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri

      - name: Build Tauri (debug)
        run: npm run tauri build -- --debug

      - name: Upload debug bundle
        uses: actions/upload-artifact@v4
        with:
          name: tauri-debug-bundle-linux
          path: src-tauri/target/debug/bundle
